name: flutter_profile_picture
description: Setting profile picture with default short name.
version: 1.0.1
homepage: "https://github.com/adityadees/flutter_profile_picture"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
