name: Build GitHub Pages
on:
  push:
    branches:
      - ci/cd
jobs:
  cd:
    runs-on: ubuntu-20.04
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.4"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter build web --release --base-href="/${{ github.event.repository.name }}/example/"
