name: Build GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  cd:
    runs-on: ubuntu-20.04
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.4"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build web --release --base-href="/${{ github.event.repository.name }}/example/"
      - run: |
          git config --global user.name '${{github.event.pusher.name}}'
          git config --global user.email '${{github.event.pusher.email}}'
          git add -f build/web
          git commit -m '[automated commit] releasing new web version.'
          git push origin `git subtree split --prefix build/web main`:gh-pages --force
